<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <ProjectReference Include="..\TestFramework.Abstractions\TestFramework.Abstractions.csproj" />
    <ProjectReference Include="..\TestFramework.Core\TestFramework.Core.csproj" />
    <ProjectReference Include="..\TestFramework.SequenceYaml\TestFramework.SequenceYaml.csproj" />
    <ProjectReference Include="..\TestFramework.Plugin.Abstractions.UI\TestFramework.Plugin.Abstractions.UI.csproj" />
    <ProjectReference Include="..\TestFramework.Plugins.BasicSteps\TestFramework.Plugins.BasicSteps.csproj" />
  </ItemGroup>
</Project>
